// Deal events
export const DEAL_AFTER_INIT_ACTOR = 'DEAL_AFTER_INIT_ACTOR';
export const DEAL_AFTER_FETCH_ACTOR = 'DEAL_AFTER_FETCH_ACTOR';
export const DEAL_PRE_SAVE_ACTOR_EVENT = 'DEAL_PRE_SAVE_ACTOR_EVENT';
export const DEAL_POST_ARIADNEXT_EVENT = 'DEAL_POST_ARIADNEXT_EVENT';
export const DEAL_AFTER_INIT_DEAL = 'DEAL_AFTER_INIT_DEAL';
export const DEAL_AFTER_FETCH_DEAL = 'DEAL_AFTER_FETCH_DEAL';
export const DEAL_AFTER_INIT_QUOTE = 'DEAL_AFTER_INIT_QUOTE';
export const DEAL_AFTER_ADD_QUOTE = 'DEAL_AFTER_ADD_QUOTE';